// Code generated by MockGen. DO NOT EDIT.
// Source: urlShortener/urlShortener/internal/adapters (interfaces: URLRepo)

// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	reflect "reflect"
	entity "urlShortener/urlShortener/internal/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockURLRepo is a mock of URLRepo interface.
type MockURLRepo struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepoMockRecorder
}

// MockURLRepoMockRecorder is the mock recorder for MockURLRepo.
type MockURLRepoMockRecorder struct {
	mock *MockURLRepo
}

// NewMockURLRepo creates a new mock instance.
func NewMockURLRepo(ctrl *gomock.Controller) *MockURLRepo {
	mock := &MockURLRepo{ctrl: ctrl}
	mock.recorder = &MockURLRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepo) EXPECT() *MockURLRepoMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockURLRepo) CreateShortURL(arg0 context.Context, arg1 *entity.URLShortener) (*entity.URLShortener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", arg0, arg1)
	ret0, _ := ret[0].(*entity.URLShortener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockURLRepoMockRecorder) CreateShortURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockURLRepo)(nil).CreateShortURL), arg0, arg1)
}

// GetShortURL mocks base method.
func (m *MockURLRepo) GetShortURL(arg0 context.Context, arg1 int) (*entity.URLShortener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortURL", arg0, arg1)
	ret0, _ := ret[0].(*entity.URLShortener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortURL indicates an expected call of GetShortURL.
func (mr *MockURLRepoMockRecorder) GetShortURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortURL", reflect.TypeOf((*MockURLRepo)(nil).GetShortURL), arg0, arg1)
}
